#!/usr/bin/env python

import os
import nvidia.cublas.lib
import nvidia.cudnn.lib


def get_location(module):
    file_path = getattr(module, "__file__", None)
    if file_path:
        return os.path.dirname(file_path)
    else:
        return list(getattr(module, "__path__", []))[0]


cublas_location = get_location(nvidia.cublas.lib)
cudnn_location = get_location(nvidia.cudnn.lib)

print(f"{cublas_location}:{cudnn_location}")
